defaults: &defaults
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  username: root
  password: root

development:
  database: vagrant_development
  <<: *defaults 


test: &TEST
  database: vagrant_test
  <<: *defaults

cucumber:
  <<: *TEST
